### ISSUE TITLE
Twisted support

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#100]
I've now been asked twice if I can port `hyper` to Twisted. Should be a matter of writing a `Connection` object for Twisted.

Might be do-able, certainly worth looking into.

**Comment by Lukasa** [comment]
Twisted has an open issue [here](https://twistedmatrix.com/trac/ticket/7460), which I should keep track of in case someone gets there before me.

**Comment by Lukasa** [comment]
Alright, [here](https://gist.github.com/Lukasa/a8b392f3f41433a9a473)'s an initial spike. This appears to work with hyper, at least a little bit.

**Comment by fredthomsen** [comment]
Interested in twisted.  Seems like you've done some work here already.  What state is this in now?

**Comment by Lukasa** [comment]
It's very different than when I opened this issue, but the progress has been really good. See [Twisted issue 7460](https://twistedmatrix.com/trac/ticket/7460).

**Comment by Lukasa** [comment]
This is, for obvious reasons, not directly relevant to this module anymore.
