### ISSUE TITLE
Split HPACK layer into own library.

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#121]
Following on from my talk at PyCon, I'd like to split the HPACK layer out into a standalone library that can be used by other projects without depending on all of `hyper`.

**Comment by sigmavirus24** [comment]
Stupid idea: What if we take advantage of having [@hapy](/hapy).

**Comment by Lukasa** [comment]
Not a bad idea at all.

**Comment by Lukasa** [comment]
This is now done.
