### ISSUE TITLE
Missing test coverage

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#137]
We're missing two tests: one that tests plaintext HTTP/2 connections work directly, without using SSL, and one that actually tests plaintext HTTP/1.1 upgrading to HTTP/2.

**Comment by fredthomsen** [comment]
I'll take care of these tomorrow morning.

**Comment by fredthomsen** [comment]
Started here #138

**Comment by Lukasa** [comment]
Resolved in #138.
