### ISSUE TITLE
HPACK Dynamic Header Table not RFC Compliant

### ISSUE THREAD

**Issue by jimcarreer** [Lukasa/hyper#141]
I'm looking at the function _add_to_header_table(self, header), specifically the section that's evicting entries from the end.  Unless I missed something, this is implemented incorrectly: you initially set header_table_size to 4096 which in the RFC7540 is the initial value for the setting HEADER_TABLE_SIZE. However, eviction from the table only occurs when an addition to the table would result in it's size being greater than MAXIMUM_HEADER_TABLE_SIZE or when the maximum header size is changed.  By default I believe a sender of headers expects no limit on the size unless otherwise specified by the receiver.  It looks like you're needlessly evicting entries from the table and keeping the header table size artificially at or below 4096. I'm not sure how this effects your implementation of HTTP2 in practice.

**Comment by Lukasa** [comment]
@jimcarreer Thanks for raising this issue!

I don't believe your reading of the RFC is correct. This is subtle and annoying, so bear with me while I try to explain. :smile:

The HPACK spec, RFC 7541, has the following to say [in section 3.2](https://tools.ietf.org/html/rfc7541#section-3.2) on this topic:

> Protocols that use HPACK determine the maximum size that the encoder is permitted to use for the dynamic table.  In HTTP/2, this value is determined by the SETTINGS_HEADER_TABLE_SIZE setting.
> 
> An encoder can choose to use less capacity than this maximum size, but the chosen size MUST stay lower than or equal to the maximum set by the protocol.

In RFC 7540, the HTTP/2 spec, [section 6.5.2 says](https://tools.ietf.org/html/rfc7540#section-6.5.2) (emphasis mine):

>   SETTINGS_HEADER_TABLE_SIZE (0x1):  Allows the sender to inform the remote endpoint of the maximum size of the header compression table used to decode header blocks, in octets.  The encoder can select any size equal to or less than this value by using signaling specific to the header compression format inside a header block (see [COMPRESSION]).  **The initial value is 4,096 octets.**

This leads to the following flow:

1. A new connection is opened. At this point I don't know what the max table size is, so I have to assume it's 4096, which is how the encoder is initialized.
2. We do the HTTP/2 preamble, which involves a SETTINGS frame being received from the remote size. If they want to increase the size of the header table, they should send us a value for SETTINGS_HEADER_TABLE_SIZE that says so appropriately. If they do that, we handle it in the `HTTP20Connection._update_settings` method.

I believe my reading of the spec is right, but I'd like to see if @tatsuhiro-t agrees with me.

**Comment by jimcarreer** [comment]
Ah I see now you're correct.  I mistook some other MAXIMUM_ setting to be the MAXIMUM_HEADER size for some reason when reading RFC7540.

**Comment by Lukasa** [comment]
Easy to do, they aren't necessarily the clearest specs. ;)

Thanks for your input!

**Comment by tatsuhiro-t** [comment]
For the record, yeah, @Lukasa is correct about the spec.

**Comment by Lukasa** [comment]
Thanks @tatsuhiro-t! :cake:
