### ISSUE TITLE
HPACK Encoder missing the never index encoding option

### ISSUE THREAD

**Issue by jimcarreer** [Lukasa/hyper#143]
This maybe because the implementation is strictly for a client, but is the pure python implementation of the encoder missing the ability to encode a "never indexed" literal / indexed name header? IE firstbyte |= 0x10?

**Comment by Lukasa** [comment]
Yes it is.

I'm happy to take an enhancement for it, but it'll probably require an API extension to pull off because there needs to be some way to flag that we should emit a 'never indexed' representation. Not really sure what the best option is: maybe an optional third element in the header tuple?

**Comment by jimcarreer** [comment]
Yeah. I'm guessing there's currently no way to specify it compay layer for nghttp either?  I think the 3rd tuple element would be a good place to start, possibly defaulting to None or Incremental when not present?

**Comment by Lukasa** [comment]
Ooh, good question: a quick look at the nghttp2 source code suggests that it also cannot flag this.

@tatsuhiro-t, are you interested in collaborating here to come up with a Python API for specifying 'never-indexed' header fields? Or does nghttp2 have some magic I'm not aware of? (If it does, I may just copy nghttp2 for compatibility.)

**Comment by Lukasa** [comment]
@jimcarreer It seems like you're interested in working on HPACK stuff: when we've worked out the API do you want to make the patch?

**Comment by jimcarreer** [comment]
I can. I'm currently working on an implemtation for my company. Was also thinking about touching up the doc strings to reference specific RFC### and Sections.

**Comment by Lukasa** [comment]
@jimcarreer Have you seen that the HPACK layer is factored out already? It's currently at [Lukasa/hpack](https://github.com/Lukasa/hpack), and is pip installable.

**Comment by jimcarreer** [comment]
@Lukasa I have, I'll submit patches to that project directly.

**Comment by Lukasa** [comment]
Brilliant. =)

Longer term I'm going to be looking to expand the scope of hyper to include a set of related projects, and I'll probably want co-maintainers for that stuff, so if you find yourself doing a lot of work on the HPACK layer I'd be happy to consider you for that role.

**Comment by jimcarreer** [comment]
@Lukasa Awesome! I was thinking the HPACK decoder could possibly use some more robust error handling as well. Unless theres some mechanism for encoded header validation before decoding I'm not seeing.

**Comment by Lukasa** [comment]
No, you're entirely right. Robust error handling would be great. The long-term goal should be to test that library to death using Hypothesis and AFL as well, but to get there we need to clarify the error paths first.

I'm working on a document that sets out my long term plan for Hyper, I should hopefully be releasing that sometime this week. Hopefully that'll lend some clarity.

For the moment, feel free to submit patches. If you're not sure something is in scope, feel free to ask me either via GitHub issue or some other contact means (I'm usually around in #python-requests on Freenode).

**Comment by tatsuhiro-t** [comment]
nghttp2 C API's header field struct is nghttp2_nv and it has flags field.  If application sets NGHTTP2_FLAG_NO_INDEX flag set, that header field is indexed with never indexed representation.
nghttp2 also automatically encodes Authorization header field and Cookie header field whose length is less than 20 bytes in never indexed representation just for safety.

nghttp2 Python HPACK API does not have this flag.  So this is the same situation in the hyper.
Thanks to the dynamic nature of Python, adding third element to name/value pair would sound good and feasible.

**Comment by tatsuhiro-t** [comment]
FYI, 20 bytes limit of Cookie header field comes from Firefox source code.  It means low entropy cookie, could be subject to brute force guessing attack.

**Comment by Lukasa** [comment]
Ok, so that feels like we have agreement there. @jimcarreer, you should feel free to take those action items, which split up as follows:

- Add a third tuple element that marks whether the item is sensitive.
- Add code for emitting the never-indexed header field for sensitive headers.
- In the Hyper client, add logic for the Authorization header and the low-entropy Cookie header field (I can do this if you're not interested).

Additionally, in parallel, we should make an enhancement to nghttp2 to accept the extra tuple field. Depending on how this pans out I may end up doing that one myself, assuming the incredibly productive @tatsuhiro-t doesn't get there before me!

Thanks @tatsuhiro-t!

**Comment by jimcarreer** [comment]
@Lukasa I'll get setup to work on that tonight after work!

**Comment by jimcarreer** [comment]
We fixed this a while back.
