### ISSUE TITLE
Trusted certs pulled over insecure channel

### ISSUE THREAD

**Issue by Prandium** [Lukasa/hyper#144]
https://github.com/Lukasa/hyper/blob/7a4d51e9be65adee677f566a05f4a787cad7ba0d/Makefile#L4 The CA bundle should only be pulled over encrypted channels during the build to reduce the likelihood of someone man-in-the-middling the request and injecting their own trusted CA into the bundle.

**Comment by Lukasa** [comment]
Certs are not pulled over an insecure channel, they're obtained from mkcert.org, as with certifi (explained in certifi/python-certifi#23). However, agreed that I should update the makefile.

**Comment by Lukasa** [comment]
Resolved in 0741b55c3e1ede9e0c902cd82bb3dd2fd25f21f1. Thanks @Prandium!

**Comment by Prandium** [comment]
Glad to hear it, thanks for the info.
