### ISSUE TITLE
TLS is not used when connecting via hyper CLI to port other then 443

### ISSUE THREAD

**Issue by direvius** [Lukasa/hyper#151]
HttpConnection does not use TLS by default (and I haven't found a way to force it through CLI): https://github.com/Lukasa/hyper/blob/development/hyper/common/connection.py#L29-L31
I expected hyper to use TLS when connecting via CLI: ```hyper GET https://myserver:3000/```, since I've mentioned ```https```.

Also, I think that might be a security issue because hyper is mostly used for HTTP/2 communication and it is expected for all such communication to be secured. Maybe its better to have ```security=True``` by default?

**Comment by Lukasa** [comment]
There's a few different things going on here.

Firstly, the hyper CLI tool. That tool should absolutely be enhanced to use the scheme to set the `secure` argument on the HTTPConnection object: we should open a bug report for that.

Second, the `HTTPConnection` object itself. You're right that the HTTPConnection object only uses TLS when port 443 is requested, or when the `secure` flag is passed. I think this is a reasonable default for the programmatic API.

Note, however, that it's not inherently expected that HTTP/2 will be used over secure connections. It's certainly the most common, but plaintext HTTP/2 is entirely allowed (and supported by Hyper).

The concrete action item I see here is to update the CLI tool to use the scheme to determine whether to pass the `secure` flag.

**Comment by Lukasa** [comment]
Proposed fix in #155.
