### ISSUE TITLE
Impossible to override default headers from CLI

### ISSUE THREAD

**Issue by direvius** [Lukasa/hyper#152]
Default headers are started with ':' and it is used to separate headers key and value in CLI arguments. And hyper does not add ':' to the specified key also. For example, hyper sets ```:authority``` to the hostname by default and you can't override it:
```
$ hyper --debug GET https://google.com:443/ authority:google.ru
...
HPACK encoding [(':method', 'GET'), (':scheme', 'https'), (':authority', 'google.com'), (':path', '/'), ('authority', 'google.ru')]
```
Or even this way:
```
$ hyper --debug GET https://google.com:443/ :authority:google.ru
...
HPACK encoding [(':method', 'GET'), (':scheme', 'https'), (':authority', 'google.com'), (':path', '/'), ('', 'authority:google.ru')]
```

**Comment by Lukasa** [comment]
Agreed, this needs working on too. =)

(The reason I'm being somewhat non-committal on these reports is because I'm currently on holiday, so I don't have a *ton* of time to work on hyper at the moment. That said, there are definitely things that need to get done.)
