### ISSUE TITLE
PyPy builds are broken

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#161]
See [this build](https://travis-ci.org/Lukasa/hyper/builds/77454850) for more.

**Comment by Lukasa** [comment]
Oh, cool, this is pyca/cryptography#299.

**Comment by sigmavirus24** [comment]
And we now know that setuptools doesn't like the extras specifiers that we could have used to say `install X version on Y python version and Z version on W python version` :(

**Comment by Lukasa** [comment]
@reaperhulk Thoughts?

**Comment by Lukasa** [comment]
Ok, well we can just feature detect this:

```python
if sys.pypy_version_info < (2, 6):
    # Force cryptography version to be lower than 1.
```
