### ISSUE TITLE
Use cryptography 1.0.1 or greater once released

### ISSUE THREAD

**Issue by sigmavirus24** [Lukasa/hyper#166]
This will allow us to remove the recently added conditional logic in setup.py to work around incompatibilities with PyPy prior to 2.6.0. Unfortunately this needs to be released first and is blocked by https://github.com/pyca/cryptography/issues/2306

**Comment by Lukasa** [comment]
Apparently @rbtcollins knows how to do a thing here, so I'll chase that up with him today.

**Comment by rbtcollins** [comment]
Hi, what thing?

**Comment by Lukasa** [comment]
In this instance, nothing anymore. =) Time has happily resolved this problem.
