### ISSUE TITLE
cannot pass stream id/request id to get_response()

### ISSUE THREAD

**Issue by nvenkat1982** [Lukasa/hyper#167]
Unable to pass stream id to get_response() when making multiple requests and trying to read responses out of order later.  Using latest hyper and have followed the example from streams section in document. 

>>> from hyper import HTTPConnection
>>> c = HTTPConnection('http2bin.org')
>>> first = c.request('GET', '/ip')
>>> second = c.request('GET', '/headers')
>>> first_resp = c.get_response(first)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_response() takes 1 positional argument but 2 were given
>>> first_resp = c.get_response('first')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

**Comment by Lukasa** [comment]
Thanks for the report @nvenkat1982! I have a fix available in #168.
