### ISSUE TITLE
Validate IPv6 support.

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#170]
According to @fredthomsen in #164, we have a number of places where we parse hostnames/ports that probably won't work when using explicit IPv6 addresses. We should fix that logic in those places and add tests to validate that IPv6 behaves appropriately.

**Comment by fredthomsen** [comment]
Started looking at where this is done. So far I only see it in the constructors, so this may be rather simple.

**Comment by fredthomsen** [comment]
Was looking through all open issues and noticed this was still here.  I believe we covered this with #172 and can be closed.

**Comment by Lukasa** [comment]
Good spot @fredthomsen, thanks!
