### ISSUE TITLE
Fix packaging pain

### ISSUE THREAD

**Issue by koobs** [Lukasa/hyper#175]
Many test related files are missing from the PyPI sdist, precluding downstream testing by users and OS packagers & porters. Among others:

- [ ] Add missing test files to sdist. tests/server.py tests/certs/* tasks.py test_* tox.ini
- [ ] Make [setup.py test command work](https://pytest.org/latest/goodpractises.html#integration-with-setuptools-test-commands) (running py.test)
- [ ] Add tests_require (pytest) in setup.py

Changes applied to address the above issues can be found in [this py-hyper port commit](https://svnweb.freebsd.org/changeset/ports/400380)

P.S If it wasn't already obvious I'm trying to test Hyper, in particular to QA the Hyper port on FreeBSD :)

**Comment by Lukasa** [comment]
@koobs Yeah, I figured! =) This hyper project has fallen a bit on the backburner recently while I've been getting Hyper-h2 up and running, but I appreciate the interest. I'll be refreshing this soonish (I hope), but in the meantime your feedback would be much appreciated.

In the short term, I'm happy to make appropriate changes to update the sdist.

**Comment by koobs** [comment]
Of course mate. I'll make a checklist :)

**Comment by koobs** [comment]
Updated title/description with checklist of changes I made downstream to have things 'just work' (not including failing tests)

**Comment by sigmavirus24** [comment]
So, I'm personally opposed to having more than one way to run the tests (i.e., making `python setup.py test` work). Tox is increasingly becoming *the* way to run tests for Python projects because of the automated virtualenv isolation and because running tests against something that isn't actually installed has proven to be fault-ridden and misleading.

**Comment by koobs** [comment]
Right now, tox runs pytest, and pytest alone just works (as it should and does). That goes for any project that uses tox (along with their favourite test collector/runner). The distinction between test collection, test running and test environment provisioning needs to be made, as well as the audience for those tests. The *requirement* for tox for anything other than development or pre-release testing is a red herring, in the same way that pep8 and flake and --cov aren't really tests_require's.

That tox is the way to run tests is a slight variation on the 'they/we do it this way, therefore this is how it should be done' argument. On it's merits, in this particular example only, the tests are being run in an isolated OS environment, with all test dependencies satisfied. The only requirement is that the package in question ought be able to 'run itself', rather than importing off PYTHON_PATH. This is trivial and has already been solved by many test tools (all the way down to individual projects hacking sys.path)

For more detail, context, and a proper breakdown see https://github.com/pyca/cryptography/issues/764#issuecomment-37152604

**Comment by Lukasa** [comment]
So, I intend to support this despite my misgivings. As a package author I *do not like* `setup.py test`, but I also accept that most downstream repackagers are insistent that it function correctly.

**Comment by Lukasa** [comment]
Ok, see #176.

**Comment by Lukasa** [comment]
@koobs BTW, with these changes made I now get a clean test run on a brand-new FreeBSD 10 system. No hangs, no failures: executed via `python setup.py test`.

```
============================= test session starts ==============================
platform freebsd10 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /root/hyper, inifile: 
collected 247 items 

test/test_SSLContext.py ...
test/test_abstraction.py ....
test/test_cli.py .............................
test/test_headers.py ...........................
test/test_http11.py ............................................
test/test_hyper.py ......................................................................................
test/test_import.py ..
test/test_integration.py ...............
test/test_integration_http11.py ......
test/test_parser.py ....
test/test_socket.py .................
test/test_windowmanager.py ..........

========================== 247 passed in 5.83 seconds ==========================
```

**Comment by koobs** [comment]
You win @Lukasa thank you :) :star:

At a minimum (and considering individuals desires/misgivings of authors), it's worth mentioning that the test command *is* canonical and allows anyone to discover & run the test suite function no matter the implementation, without hunting for special files, tools or documentation, in the same way *make check* for autotools projects does. test_suite and tests_requires enables exactly that.

**Comment by koobs** [comment]
@Lukasa  I will now start porting hyper-h2 ;)

**Comment by koobs** [comment]
@Lukasa Very interesting on the no hangs, I'll test master in the port.
