### ISSUE TITLE
test_integration*.py tests hang with Python w/o IPv6

### ISSUE THREAD

**Issue by koobs** [Lukasa/hyper#177]
server.py [creates an AF_INET6 socket on _start_server](https://github.com/Lukasa/hyper/blob/development/test/server.py#L60) which hangs when run on Python that doesn't support, was built without, or runs on a system without IPv6 support.

This results in test_integration*.py tests hanging. Installing and using pytest-timeout produced the following stderr traceback, and stack:

![pytest-timeout-traceback txt](https://cloud.githubusercontent.com/assets/1011612/10810350/2842e780-7e54-11e5-8a20-4d285e7d80d9.png)

Edit: couldn't upload the full (txt) log without repository write permissions, so here's a screenshot :)

Rebuilding Python w/ IPv6 support results in a clear test run:

```
 250 passed, 1 skipped, 1 pytest-warnings in 17.20 seconds 
```

**Comment by Lukasa** [comment]
Ok, pushed a fix for this to `development`.
