### ISSUE TITLE
ssl.OP_NO_COMPRESSION raises AttributeError on Python 2.7.10 + OS X 10.11

### ISSUE THREAD

**Issue by ushuz** [Lukasa/hyper#178]
AttributeError was raised when I was following the example in documentation, using OS X 10.11 built-in Python 2.7.10.

```
Python 2.7.10 (default, Aug 22 2015, 20:33:39)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from hyper import HTTPConnection
>>>
>>> conn = HTTPConnection('http2bin.org:443')
>>> conn.request('GET', '/get')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/John/venv/lib/python2.7/site-packages/hyper/common/connection.py", line 98, in request
    method=method, url=url, body=body, headers=headers
  File "/Users/John/venv/lib/python2.7/site-packages/hyper/http11/connection.py", line 164, in request
    self.connect()
  File "/Users/John/venv/lib/python2.7/site-packages/hyper/http11/connection.py", line 128, in connect
    sock, proto = wrap_socket(sock, host, self.ssl_context)
  File "/Users/John/venv/lib/python2.7/site-packages/hyper/tls.py", line 36, in wrap_socket
    _context = init_context()
  File "/Users/John/venv/lib/python2.7/site-packages/hyper/tls.py", line 91, in init_context
    context.options |= ssl.OP_NO_COMPRESSION
AttributeError: 'module' object has no attribute 'OP_NO_COMPRESSION'
```

**Comment by Lukasa** [comment]
Sadly, `hyper` *cannot* function on the built-in OS X Python. This is because it's linked again OpenSSL 0.9.8zg, which does not support any of the TLS functionality required for HTTP/2. It is simply impossible to configure the SSL securely.

I recommend either installing and using Python from Homebrew, or installing a newer OpenSSL from Homebrew and using PyOpenSSL, linked against that newer OpenSSL.

Sorry!

**Comment by ushuz** [comment]
@Lukasa Thanks for your quick response and advice. I will give it a try. However, it may be better if a caution could be provided for OS X users in docs.

**Comment by Lukasa** [comment]
That's a good idea. =) I'll welcome a pull request that adds it!

**Comment by Johnykutty** [comment]
@Lukasa Even in my python 3.5 its showing error.
Full error is

```
Traceback (most recent call last):
  File "/Users/johnny/Desktop/Johnykutty/Python/APNSProvider.py", line 20, in <module>
    c.request('POST', '/post', headers = httpHeaders, body = params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hyper/common/connection.py", line 98, in request
    method=method, url=url, body=body, headers=headers
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hyper/http11/connection.py", line 164, in request
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hyper/http11/connection.py", line 128, in connect
    sock, proto = wrap_socket(sock, host, self.ssl_context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hyper/tls.py", line 36, in wrap_socket
    _context = init_context()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hyper/tls.py", line 91, in init_context
    context.options |= ssl.OP_NO_COMPRESSION
AttributeError: module 'ssl' has no attribute 'OP_NO_COMPRESSION'
```

How can I fix this?

**Comment by Lukasa** [comment]
@Johnykutty Can you open a Python shell and show me the result of:

```python
import ssl
print(ssl.OPENSSL_VERSION)
```

**Comment by Johnykutty** [comment]
@Lukasa 
Its  still 0.9.8zg 
```>>> import ssl
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 0.9.8zg 14 July 2015
>>> ```

**Comment by Lukasa** [comment]
Yup, so that's too old.

You really need OpenSSL 1.0.2 or greater. You can get it for OS X from Homebrew. You'll then need to compile a new version of Python that links against it. Alternatively, the version of Python you get from python.org may use a better OpenSSL.

**Comment by Johnykutty** [comment]
I installed python from python.org (3.5). Actually I can connect to http2bin.org even with 2.7. But error occurs when I am trying to connect to apple push notification provider api

**Comment by Lukasa** [comment]
@Johnykutty Are you connecting to http2bin.org not via port 443? Because that won't use TLS and so you won't encounter this problem, and 2.7 will work fine.

Note that 2.7.9 and later will work fine if you compile them against a newer OpenSSL.

**Comment by Johnykutty** [comment]
Oh Yeah that is the problem. I am newbie to python development. Can you give me any reference  to do as you said? 

My python version is 2.7.10
```
$ python --version
Python 2.7.10
```

**Comment by Lukasa** [comment]
@Johnykutty Well, if you install [Homebrew](http://brew.sh/), you can `brew install openssl` which will get you OpenSSL 1.0.2e. At that point you'll need to install a Python that links against it. You can either do `brew install python`, which will get you 2.7.11 linked against OpenSSL, or you can use [pyenv](https://github.com/yyuu/pyenv).

**Comment by Lukasa** [comment]
Note if you use pyenv that you'll need to put Homebrew's OpenSSL into your linker path, by running (e.g.) `env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pyenv install 2.7.11`

**Comment by Johnykutty** [comment]
Thank you @Lukasa, But I tried this already these commands. Now it is saying that python-2.7.11 already installed, it's just not linked. 

```
$ brew install openssl
Warning: openssl-1.0.2e already installed
$ brew install python
Warning: python-2.7.11 already installed, it's just not linked
```

**Comment by Johnykutty** [comment]
I found the way to link it 
```brew link --overwrite python```

Thank you @Lukasa  for the help :)
