### ISSUE TITLE
Why not use SSLContext.load_default_certs in tls.init_context?

### ISSUE THREAD

**Issue by evertlammerts** [Lukasa/hyper#195]
You've probably given this some thought and I may have missed the documentation. Why are you shipping CA certificates and loading them in tls.init_context, rather than using SSLContext.load_default_certs?

**Comment by Lukasa** [comment]
The short answer is that `load_default_certs` doesn't work properly on Mac OS X or Windows.

The long answer is that using the default verification logic on all platforms is tricky. It's something I'm working on: see the discussion in kennethreitz/requests#2966. The hope is that with PyOpenSSL we'll be able to properly use the system trust stores on all platforms properly, as things like Chrome do, and then we'll be in a much better place.

**Comment by evertlammerts** [comment]
Wow, CA trust is a much bigger mess than I already thought.

About shipping the bundle in Hyper: I see the shipped bundle is only used if the user doesn't provide their own `SSLContext`. Wouldn't it be more correct to require them to explicitly specify whether they want to use the shipped bundle rather than the default (ie `SSLContext.load_default_certs`, since that's used in `ssl.create_default_context`)? I know (now) lots may be wrong with whatever that returns, but given that that is what would be used if they'd use SSLContext directly, doesn't it make more sense for the user to trust that than whatever Hyper shipped during install?

One way of doing that: `ssl_context` could be a required argument for `HTTP20Connection.__init__`, requiring the user to create one. (The `secure` argument and the check for 443 are then no longer needed - if ssl_context is `None` we're not using TLS.) A convenience method could create one for the user, explicitly specifying the use of the shipped bundle, defaulting to False (something like tls.create_default_context(use_hyper_cabundle=False)). If it's False, default to `ssl.create_default_context`.

The advantage would be that you at least force the user to think about it, at the cost of having SSL “just work” without knowing at what price.

Asking a thousand people would probably get you a thousand of opinions when it comes down to trust. So don't feel in any way obliged to reply. Great job on the library!

**Comment by Lukasa** [comment]
Right now I'm aiming to have it "just work", but it does need to be re-evaluated. At some point this library will get subsumed into the broader [Hyper project](http://python-hyper.org), and at that point I'll want to re-evaluate our policy on TLS. In the short term, "just works" is a suitable bar for me I think. =)

With that said, the idea of using a factory method here is a good one, and is probably what the eventual shape of the solution will be.
