### ISSUE TITLE
http response is not accepted by browser

### ISSUE THREAD

**Issue by derekchentrendmicro** [Lukasa/hyper#209]
I created a simple HEADERS response followed by a DATA frame to the browser (both firefox and chrome) 

hpack_encoder = Encoder()
frm_headers = HeadersFrame(stream_id)
headers = {":status": 200,"content-length": 2,"content-type": "text/plain"}
encoded_headers = hpack_encoder.encode(headers,huffman=False)
frm_headers.flags.add('END_HEADERS')
ssl_sock.send(frm_headers.serialize())
ssl_sock.send(frm_data)

and browser didn't show anything. so I dumped the content of encoded_headers and got '\\\x012_\ntext/plain\x88'. If I move the byte '\x88', which is ":status: 200", to the head, i.e. '\x88\\\x012_\ntext/plain', both browsers display the response data correctly. Thus I think hpack encoder should place the pseudo-header fields in the beginning of HEADERS frame. RFC 7540 mentions this in section 8.1.2.1,

> All pseudo-header fields MUST appear in the header block before regular header fields. Any request or response that contains a pseudo-header field that appears in a header block after a regular header field MUST be treated as malformed

**Comment by Lukasa** [comment]
So, that's an interesting idea. Right now, HPACK simply does not police this: it allows the possibility of emitting header fields that are not in order. That's obviously somewhat problematic whenever someone passes in a dictionary which can lose the order.

My inclination is to split the difference: if you pass HPACK a dictionary it will 'fix' the order for you, but if you pass an iterable of two-tuples it'll leave them alone. How does that sound to you @derekchentrendmicro?

(Also, note that HPACK is now a separate library with its own repository at [github.com/python-hyper/hpack](https://github.com/python-hyper/hpack).)

**Comment by Lukasa** [comment]
You can see the proposed change at python-hyper/hpack#32. If it resolves your problem @derekchentrendmicro, then please let me know and I'll aim to ship a release containing the fix.

**Comment by Lukasa** [comment]
Also, fwiw @derekchentrendmicro, unless you're really trying to do something clever you may find [hyper-h2](http://python-hyper.org/h2/) is the tool you want, rather than constructing frames yourself.

**Comment by derekchentrendmicro** [comment]
1. it's good, especially for testing, to have the choice to preserve the order or not. 
2. I left my comment in your commit
3. Thanks for introducing me hyper-h2. It looks interesting. I'll see if it can fulfill my needs.
