### ISSUE TITLE
A question about Interface Document

### ISSUE THREAD

**Issue by wangmengcn** [Lukasa/hyper#210]
hi,when I read hyper intereface document at https://hyper.readthedocs.org/en/latest/api.html, a problem confused me.
HTTPConnection's parameter port——"The port to connect to. If not provided and one also isn’t provided in the host parameter, defaults to 443".
I think  something wrong is there, it should default to 80 not 443 in practice.
Looking forward your answer and wish you have a nice day!

**Comment by Lukasa** [comment]
Good spot, the documentation is wrong: it does default to 80. Do you feel like changing the documentation there?

**Comment by wangmengcn** [comment]
I'd like to ,but I don't know how to do that =.=
