### ISSUE TITLE
Issues with Amazon Alexa Voice Service

### ISSUE THREAD

**Issue by sammachin** [Lukasa/hyper#225]
Amazon have released a new API for Alexa but its HTTP/2 only, this is my first attempts with http/2 but there seems to be a problem with accessing the amazon API using hyper, other test servers work fine and I can also connect using curl, I get this error using either hyper on the command line or in a script.
(Token redacted to XXXXX, message me if you need a token to test with)

root@AlexaPiV2:~/curl-7.48.0# hyper --debug GET https://avs-alexa-na.amazon.com/v20160207/directives 'Authorization:Bearer  XXXXXXXXXXXXXXXX'
Url Info: {'secure': True, 'fragment': None, 'netloc': 'avs-alexa-na.amazon.com', 'host': 'avs-alexa-na.amazon.com', 'query': None, 'path': '/v20160207/directives', 'scheme': 'https', 'port': 443}
Commandline Argument: Namespace(_url='https://avs-alexa-na.amazon.com/v20160207/directives', body=None, debug=True, h2=False, headers={'Authorization': 'Bearer  XXXXXXXXXXXX'}, items=[<hyper.cli.KeyValue object at 0x766c45f0>], method='GET', url=<hyper.cli.UrlInfo object at 0x766c4710>)
Selected protocol: None
Traceback (most recent call last):
  File "/usr/local/bin/hyper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/hyper/cli.py", line 244, in main
    data = request(args)
  File "/usr/local/lib/python2.7/dist-packages/hyper/cli.py", line 234, in request
    response = conn.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 124, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 199, in get_response
    response = self.parser.parse_response(self._sock.buffer)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/parser.py", line 52, in parse_response
    version, status, reason = temp_buffer[0:index].split(None, 2)
ValueError: need more than 1 value to unpack
root@AlexaPiV2:~/curl-7.48.0#

**Comment by Lukasa** [comment]
Thanks for raising this issue!

So it seems like Amazon has done the same as Apple's push notifications service, and only offers ALPN for the negotiation. Your machine seems like it doesn't have a new enough OpenSSL to negotiate with ALPN, so hyper concludes that it can't safely use HTTP/2: Amazon concludes otherwise.

The current development branch has a `force_proto` kwarg you can use with the API, and should have a `--h2` argument for the CLI to force the direct use of HTTP/2. Mind trying those out?

**Comment by sammachin** [comment]
Sure, can I just check how to install the dev branch to get the CLI? for this one I just did pip install

**Comment by Lukasa** [comment]
Sure, run `pip install git+https://github.com/Lukasa/hyper.git@development`

**Comment by sammachin** [comment]
root@AlexaPiV2:~# pip install git+https://github.com/Lukasa/hyper.git@development
Downloading/unpacking git+https://github.com/Lukasa/hyper.git@development
  Cloning https://github.com/Lukasa/hyper.git (to development) to /tmp/pip-wcxAmZ-build
  Running setup.py (path:/tmp/pip-wcxAmZ-build/setup.py) egg_info for package from git+https://github.com/Lukasa/hyper.git@development
    error in hyper setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in hyper setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-wcxAmZ-build
Storing debug log for failure in /root/.pip/pip.log
root@AlexaPiV2:~# cat /root/.p
.pip/     .profile  
root@AlexaPiV2:~# cat /root/.pip/pip.log 
------------------------------------------------------------
/usr/bin/pip run on Mon Apr 18 10:49:43 2016
Downloading/unpacking git+https://github.com/Lukasa/hyper.git@development
  Cloning https://github.com/Lukasa/hyper.git (to development) to /tmp/pip-wcxAmZ-build
  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git clone -q https://github.com/Lukasa/hyper.git /tmp/pip-wcxAmZ-build
  Running command /usr/bin/git show-ref
  db66a7a8da397be9b85d83559e955ec069e3a813 refs/heads/development
  db66a7a8da397be9b85d83559e955ec069e3a813 refs/remotes/origin/HEAD
  7e671d09b18cc3e9664b35cfb7f6c75e4e29690e refs/remotes/origin/concurrency
  db66a7a8da397be9b85d83559e955ec069e3a813 refs/remotes/origin/development
  fd6badec13e495644a68bf3a4b2b75527f4797cf refs/remotes/origin/master
  e0b4efc067b12a26852847d4bc8057a4ca4b3dbd refs/remotes/origin/state
  62b1cf5a4af6ce1ccd27d398444e0ce8c782ab98 refs/tags/v0.0.2
  3c8ae0db53bf4f2803872b6c478fc03a1a6cdd1a refs/tags/v0.0.3
  ec527e872af38f4fc83dea02d17d63f8b5ec60fe refs/tags/v0.0.4
  308be18d5db1bc5218f14884b7b1cb78105e1f21 refs/tags/v0.1.0
  05cfc213ed189a48279dab27efd2d35d536b02c9 refs/tags/v0.1.1
  8d1eb85fdfc57e2dc3f43964236857edd053685f refs/tags/v0.1.2
  951756c152aac7819b13962e44b62a13de935d6c refs/tags/v0.2.0
  c5775cb31b218beda5c14eb6b10ca51c92109302 refs/tags/v0.2.1
  d374985f3971f03be7b07890c7290f24c804bb09 refs/tags/v0.2.2
  b4ca99e7795847abf978c372c070d33ea324b1d9 refs/tags/v0.3.0
  e4f57e7ec12b03747e42f2f883211e96851347b9 refs/tags/v0.3.1
  7202f24fdbf76db1d2d53293037dc9fe6ac8aa22 refs/tags/v0.4.0
  fd6badec13e495644a68bf3a4b2b75527f4797cf refs/tags/v0.5.0
  Running command /usr/bin/git rev-parse HEAD
  db66a7a8da397be9b85d83559e955ec069e3a813
  Running setup.py (path:/tmp/pip-wcxAmZ-build/setup.py) egg_info for package from git+https://github.com/Lukasa/hyper.git@development
    error in hyper setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in hyper setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-wcxAmZ-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-wcxAmZ-build

**Comment by Lukasa** [comment]
What pip version do you have? Seems like it can't handle the pip version specifiers being used.

**Comment by sammachin** [comment]
root@AlexaPiV2:~# pip -V

pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)


I'm running on a RaspberryPi with the latest Raspian build

**Comment by Lukasa** [comment]
Yeah, pip 1.5.6 is quite old. This might be fixable on the development branch but I'm currently on my phone at an airport so I can't check until later. In the meantime, if you're familiar with virtualenv you can create one of those and then upgrade pip inside it (`pip -U pip`) then try the install.

**Comment by sammachin** [comment]
Thanks, I'll have a play later, should get back to the day job! have a good
flight

**Comment by sammachin** [comment]
Got the dev branch installed in a venv, however now I'm getting a new error:
`(newpip) root@AlexaPiV2:~/newpip# hyper --debug --h2 GET https://avs-alexa-na.amazon.com/v20160207/directives 'Authorization:Bearer XXXX'
Url Info: {'secure': True, 'fragment': None, 'netloc': 'avs-alexa-na.amazon.com', 'host': 'avs-alexa-na.amazon.com', 'query': None, 'path': '/v20160207/directives', 'scheme': 'https', 'port': 443}
Commandline Argument: Namespace(_url='https://avs-alexa-na.amazon.com/v20160207/directives', body=None, debug=True, h2=True, headers={'Authorization': 'Bearer XXXX'}, items=[<hyper.cli.KeyValue object at 0x7653f090>], method='GET', url=<hyper.cli.UrlInfo object at 0x76518990>)
Selected NPN protocol: None
Traceback (most recent call last):
  File "/root/newpip/bin/hyper", line 9, in <module>
    load_entry_point('hyper==0.5.0', 'console_scripts', 'hyper')()
  File "/root/newpip/local/lib/python2.7/site-packages/hyper/cli.py", line 251, in main
    data = request(args)
  File "/root/newpip/local/lib/python2.7/site-packages/hyper/cli.py", line 240, in request
    conn.request(args.method, args.url.path, args.body, args.headers)
  File "/root/newpip/local/lib/python2.7/site-packages/hyper/http20/connection.py", line 178, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "/root/newpip/local/lib/python2.7/site-packages/hyper/http20/connection.py", line 367, in endheaders
    self.connect()
  File "/root/newpip/local/lib/python2.7/site-packages/hyper/http20/connection.py", line 251, in connect
    assert proto in H2_NPN_PROTOCOLS or proto == H2C_PROTOCOL
AssertionError`

**Comment by Lukasa** [comment]
Ah, yes. Ok, that's a real bug. I'll take a swing at it in the next 24 hours: should be an easy fix.

**Comment by sammachin** [comment]
oh cool thanks :)

**Comment by Lukasa** [comment]
@sammachin I believe I've fixed this: want to try again with the new tip?

**Comment by nicholasjconn** [comment]
I've been following this thread since its inception, and I'm happy to say that hyper is now working just fine with Amazon's AVS.

Thanks for actively developing hyper and keeping up on this kind of stuff! It is much appreciated.

**Comment by Lukasa** [comment]
@nicholasjconn Happy to do it! I've got a release of hyper-h2 upcoming: when I've shipped that, I should have some time to spare to get this library into shape for a new release.

**Comment by sammachin** [comment]
Yep seems to be working, thanks for sorting this so quickly :)

Now to try and decipher the rest of this AVS api!

**Comment by joshdover** [comment]
Correct me if I'm wrong, but if I'm using hyper with the requests adapter, it seems there's no way to to set the `force_proto` option? What openssl packages do I need to change on my machine to just make this work without that option?

**Comment by Lukasa** [comment]
Correct; that work is sitting in #214 and is as-yet unfinished. To get this to work without that option you'll need OpenSSL 1.0.2. What OS are you using?

**Comment by joshdover** [comment]
I'm on raspbian (debian) jessie, having a hard time finding a package for it. Might just trying to build it unless you have any tips.

**Comment by joshdover** [comment]
Hm, installed openssl 1.0.2h from debian/testing and I'm still getting the same error. Tried recompiling python 3.5 as well. Any ideas?

**Comment by Lukasa** [comment]
@joshdover To be clear, what error are you getting? Also, can you please confirm that the Python you're using is linked against your new OpenSSL? `python -c "import ssl; print ssl.OPENSSL_VERSION"`.
