### ISSUE TITLE
feature request: response.raise_for_status()?

### ISSUE THREAD

**Issue by pawelmhm** [Lukasa/hyper#241]
python-requests have this nice feature response.raise_for_status() that will throw error in case response status is >= 400. Would be nice to have something like this. Usage example could go like this

```python
from hyper import HTTPConnection
c = HTTPConnection('www.example.com')
path = '/api/will/throw/error'
c.request('GET', path)
resp = c.get_response()
resp.raise_for_status()
# traceback here if it's not 200 
print(resp)
```

**Comment by Lukasa** [comment]
Yup, that's a nice feature. However, this library is quite a bit lower level than requests.

Have you considered using the [Requests adapter](https://hyper.readthedocs.io/en/latest/quickstart.html#requests-integration)?

**Comment by pawelmhm** [comment]
> Have you considered using the Requests adapter?

ah thanks for useful hint, will try that. 

> However, this library is quite a bit lower level than requests.

hmm yeah you're right, feel free to close this if you think hyper is too high level for that.

**Comment by Lukasa** [comment]
I think the goal for hyper, at least in this kind of use case, should be to integrate cleanly with requests. That means that we can delegate things like this to requests itself.

Thanks for the suggestion though!
