### ISSUE TITLE
install failed with python 2.6.6 or python  2.7.4

### ISSUE THREAD

**Issue by hupantingxue** [Lukasa/hyper#242]
hyper]$ ~/python/bin/python2.6 setup.py  install
`error in hyper setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers`

**Comment by Lukasa** [comment]
Thanks for this!

Python 2.6 is not a supported Python version for hyper: it is no longer receiving security updates and is not supported by the upstream development team, so the cost of supporting it for me is simply too high. If you'd like Python 2.6 support from hyper please reach out to your distributor and ask them to formally get in contact or do the backporting work themselves.

As for Python 2.7.4, this is almost certainly the result of you having a `pip` or `setuptools` that are sufficiently old that they do not recognise the `~=` syntax used [here](https://github.com/Lukasa/hyper/blob/development/setup.py#L56). Again, I recommend upgrading your setuptools or pip. Generally speaking, a Python version as old as 2.7.4 is likely to have several bugs in it that I'm not willing to support or work around, given that Python 2.7.11 is now the current most-recent version.

**Comment by hupantingxue** [comment]
ok,thx
