### ISSUE TITLE
Allow HTTP defined methods only

### ISSUE THREAD

**Issue by kracekumar** [Lukasa/hyper#268]
HTTP defined methods are `GET, HEAD, POST, PATCH, DELETE, TRACE, OPTIONS, CONNECT`. `hyper` CLI doesn't validate the user inputted methods.

```bash
krace@Kracekumars-MacBook-Pro ~/c/hyper-h2> (hyper-h2) hyper --h2 GET23 http://http2bin.org/get
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

Argument parser `add_argument` takes an argument `choices`. The `choices` can hold the list of allowed HTTP defined methods. As of now, using lower case HTTP methods cause unexpected behaviour.

```
krace@Kracekumars-MacBook-Pro ~/c/hyper-h2> (hyper-h2) hyper --h2 get http://http2bin.org/get
<html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    Invalid Method 'Invalid HTTP method: 'get''
  </body>
</html>
```

I am happy to send a PR.

**Comment by Lukasa** [comment]
So I'd like to allow arbitrary methods: there are many extensions to HTTP that use custom HTTP methods. However, we should absolutely just uppercase the method we're given.
