### ISSUE TITLE
Support plaintext HTTP/2 using HTTP Upgrade

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#28]
It would be nice if we could initiate HTTP/1. and then upgrade to HTTP/2 if the response allows us to.

This basically requires writing a HTTP/1.1 stack: I doubt aiohttp gives me the needed control.

**Comment by Lukasa** [comment]
Alright, this is possible now that I have HTTP/1.1 merged.

**Comment by fredthomsen** [comment]
Long-time lurker here looking to contribute and I started taking a look at this.  Wanted to get your take to make sure I wasn't way off base before I try and finish it off.  Thanks

https://github.com/lukasa/hyper/compare/development...fredthomsen:plaintext_http20_via_http11_upgrade

**Comment by Lukasa** [comment]
@fredthomsen This looks amazing! Go ahead and open a pull request with the work you have now, we can use it to track the development and provide feedback. =D

**Comment by fredthomsen** [comment]
@Lukasa  #136

**Comment by Lukasa** [comment]
Supported!
