### ISSUE TITLE
Opening connection with HTTPS Schema fail

### ISSUE THREAD

**Issue by yeralin** [Lukasa/hyper#283]
Whenever I try to HTTP20Connection('https://example.com'), it throws me an error:

AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by Lukasa** [comment]
Can you please provide the full traceback?

**Comment by Lukasa** [comment]
Oh, nevermind.

The documentation for [HTTP20Connection](https://hyper.readthedocs.io/en/latest/api.html#hyper.HTTP20Connection) states:

> `host`: The host to connect to. This may be an IP address or a hostname, and optionally may include a port: for example, `'http2bin.org'`, `'http2bin.org:443'` or `'127.0.0.1'`.

That means you should use `HTTP20Connection('example.com', port=443)`.
