### ISSUE TITLE
Relationship with python-hyper

### ISSUE THREAD

**Issue by scribu** [Lukasa/hyper#292]
While looking for HTTP/2 libraries, I encountered two libraries with "hyper" in the name (and even the same logo in the README):

* https://github.com/Lukasa/hyper (this one)
* https://github.com/python-hyper/hyper-h2

I understand that hyper-h2 is meant to be lower-level, yet I don't see it listed as a dependency in the higher-level hyper lib.

Is hyper deprecated?

**Comment by Lukasa** [comment]
hyper-h2 is definitely a dependency of this library: [here it is](https://github.com/Lukasa/hyper/blob/development/setup.py#L81)!

This naming confusion is really annoying but it stems from how these things got to be. This library was the first one I wrote. When I encountered problems with code re-use, [hyperframe](https://github.com/python-hyper/hyperframe) and [hpack](https://github.com/python-hyper/hpack) were both pulled out of it and moved into a common organisation. I then started h2 as a sans-IO approach to HTTP/2 that could be re-used by this library, which it now is.

Ultimately, this library is the progenitor of the name. Formally, hyper-h2 is better-called just 'h2'.
