### ISSUE TITLE
Ignore SSL checking in HTTP20Adapter

### ISSUE THREAD

**Issue by hustshawn** [Lukasa/hyper#323]
I have a self-signed SSL nginx server that support HTTP2. Normally when I call the api to the server with `requests`, I will use `verify=False` to ignore the SSL checking.

After I realised `requests` itself does not support HTTP2, then I applied your `HTTP20Adapter`, how I can achieve the same result by ignore the SSL checking but transmit the request with HTTP2?

```python
import requests
from hyper.contrib import HTTP20Adapter
s = requests.Session()
s.mount("https://myserver", HTTP20Adapter())
# 
# s.verify = False
r = s.get("https://myserver/endpoint")
# or
# r = s.get("https://myserver/endpoint", verify=False)

```
It will got `SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)`

The code below is basically same as your `requests integration` in your document.
Any suggestions?

**Comment by Lukasa** [comment]
Thanks for raising this issue! This will be resolved by #321.
