### ISSUE TITLE
HTTP20Adapter doesn't convert headers from ```bytes``` to ```str```ings

### ISSUE THREAD

**Issue by KOLANICH** [Lukasa/hyper#324]
HTTP20Adapter doesn't convert headers and their keys from ```bytes``` to ```str```ings. It breaks compatibility with ```requests``` where headers labels are ```str```ings. Is this by design?

**Comment by Lukasa** [comment]
No, this is a newer problem that was introduced because we weren't paying enough attention. It should be a simple fix: simply pass the appropriate encoding argument to the HTTP2 connection class.

**Comment by Lukasa** [comment]
Ah, hang on, that's not it. The HTTP/1.1 stack appears to always provide bytes headers, which may be the actual problem here. We can probably just fix that, but it'll be a breaking change which I'm reluctant to just leap into. I'd rather fix it along with removing our custom parser in favor of h11.
