### ISSUE TITLE
Hyper and h2 pip installs incompatible

### ISSUE THREAD

**Issue by wbl** [Lukasa/hyper#327]
To reproduce: use pip to install hyper and h2.
Run any program relying on hyper.
Watch as an import breaks things.

**Comment by Lukasa** [comment]
Can you provide the output of `pip freeze`?

**Comment by wbl** [comment]
$pip freeze
appdirs==1.4.3
certifi==2017.4.17
Cython==0.25.2
enum34==1.1.6
h2==3.0.1
hpack==3.0.0
hyper==0.7.0
hyperframe==3.2.0
packaging==16.8
pyparsing==2.2.0
six==1.10.0

**Comment by Lukasa** [comment]
Your version of h2 is outside the bounds of what is allowed by hyper. This is a pip problem, not a hyper one: if you just `pip install hyper` you'll get a compatible version.
