### ISSUE TITLE
Response knows whether the request went over HTTP/1.x or HTTP/2

### ISSUE THREAD

**Issue by lawnmowerlatte** [Lukasa/hyper#330]
As a user, I'd like to know whether the connection was successfully sent over HTTP/2 or if it fell back to HTTP/1.x. This can be useful for debugging/testing. Storing the class of the HTTPConnection object used seems the most straightforward option, but I'm open to alternatives.

**Comment by nateprewitt** [comment]
Hey @lawnmowerlatte, I believe this information was surfaced in #296 and should be available on all Connection and Response objects. You can access it via the version attribute.

**Comment by lawnmowerlatte** [comment]
Ah, I see now. I need this info when using the `requests` plugin, I didn't see that the Hyper object gets embedded into the `response.raw`. After doing a bit of digging, I found that I can do `response.raw.version` to get the info. No need for any changes. Thanks @nateprewitt

**Comment by nateprewitt** [comment]
No problem, glad you were able to find what you needed 😊
