### ISSUE TITLE
Implement compressors composition

### ISSUE THREAD

**Issue by KOLANICH** [Lukasa/hyper#338]
https://tools.ietf.org/html/rfc7231#section-3.1.2.2
>If one or more encodings have been applied to a representation, the sender that applied the encodings MUST generate a Content-Encoding header field that lists the content codings in the order in which they were applied.

**Comment by Lukasa** [comment]
I don't see any need to support this for compressors. No-one in their right mind does multiple-compression, this has literally never come up in Requests which has enormous usage, so I think we simply don't need to support it.

**Comment by KOLANICH** [comment]
>No-one in their right mind does multiple-compression

I think this part of spec is such because they wanted to allow the features of tweaking compression for data types (s.a. machine code or natural language text) by applying filters.

**Comment by Lukasa** [comment]
Sure, but that's not really super-relevant in this case. Unless we can point to anyone *actually* deploying multiple compressors in one go, it doesn't really matter whether we support it or not.

**Comment by KOLANICH** [comment]
I think that people expect spec impls to follow the specs. If someone started to experiment with compression filters he would have encountered the bug.

**Comment by Lukasa** [comment]
Ok, what compression filter pipeline are you expecting to see?

**Comment by KOLANICH** [comment]
Don't know, for now there are no filters defined in the rfc. For example we can think about the filters defined in https://tukaani.org/xz/xz-file-format.txt.

**Comment by Lukasa** [comment]
So my general position on this is that there is no need for us to ship code to support hypothetical use-cases. *As deployed* the `content-encoding` field is basically used only for monolithic compression algorithms. There are no defined specifications for compression algorithms that can be chained. As-and-when they are, we can revisit this decision, but I'm disinclined to add support for a use-case that is not deployed, and has never been deployed in the 20 year history of this protocol.

**Comment by KOLANICH** [comment]
Then we should not walk the array, but just take the first item in #336

**Comment by Lukasa** [comment]
Fair enough, sounds like a reasonable position. =)
