### ISSUE TITLE
Is there a way to disable server certificate validation?

### ISSUE THREAD

**Issue by xianglisegue** [Lukasa/hyper#340]
Hi,
I am trying to use HTTP20Adapter with Requests. With Requests, I can simply use verify=False to disable validating server certificate, but it seems I can't figure out how to achieve this with HTTP20Adapter.

Looking at the source, HTTP20Adapter initializes  a ssl_context, depends on the value of "cert" passed in.

SSLContext

Create a new SSLContext that is correctly set up for an HTTP/2 connection. This SSL context object can be customized and passed as a parameter to the HTTPConnection class. Provide your own certificate file in case you don’t want to use hyper’s default certificate. The path to the certificate can be absolute or relative to your working directory.

cert_path – (optional) The path to the certificate file of “certification authority” (CA) certificates

It seems to me I can either use hyper's CA or my own, but can't disable it?

Thank you very much for the help
-Xiang

**Comment by Lukasa** [comment]
The current master branch has this support: try running `pip install -U git+https://github.com/Lukasa/hyper.git` and see if that resolves your issue.

**Comment by xianglisegue** [comment]
Yes, now the ‘verify=False’ option used in Requests’ session object appears to be working fine with HTTP20Adapter after the update!

 

Thank you very much for the help!

 

-Xiang
