### ISSUE TITLE
how to use hyper send a multiple part http request

### ISSUE THREAD

**Issue by xiaoxiaojuan** [Lukasa/hyper#362]
for example my body is like below

I want to send one by one, for I want to send the json part and then the audio part and then the end boundary., and then get the response .

Not sure how to do it

------------------------------4ebf00fbcf09
Content-Disposition: form-data; name="metadata"
Content-Type: application/json; charset=UTF-8

{data}

------------------------------4ebf00fbcf09
Content-Disposition: form-data; name="audio"
Content-Type: application/octet-stream
audio data
------------------------------4ebf00fbcf09--

**Comment by Lukasa** [comment]
You would need to construct the body yourself, probably by using a library, and then call `request` with the appropriate body.
