### ISSUE TITLE
how to iterate over read(amt,decode_content=True)?

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [Lukasa/hyper#373]
Hi all,
i wanted to read the response in a block of data units.
So, is there a way to use the read(DATA_BLOCK_SIZE) iteratively till all the response data is read?

(Just like the 'iter_content(CHUNK_SIZE)' in the [requests](https://github.com/requests/requests/blob/e4fc3539b43416f9e9ba6837d73b1b7392d4b242/requests/models.py#L724) library)

Thanks,
Raj

**Comment by sigmavirus24** [comment]
Perhaps

```py
chunk = read()
while chunk:
    # do stuff
    chunk = read()
```

**Comment by Lukasa** [comment]
Yeah, call `read` repeatedly.

**Comment by deshmukhrajvardhan** [comment]
Thanks 
https://github.com/sigmavirus24 and 
https://github.com/Lukasa

It works fine.
