### ISSUE TITLE
SOCKS(5) proxy support

### ISSUE THREAD

**Issue by matsjoyce** [Lukasa/hyper#397]
Is there any plans or interest in adding SOCKS proxies to hyper? Currently trying to use TOR results in a:
```
hyper.common.exceptions.ProxyError: Tunnel connection failed: 501 Tor is not an HTTP Proxy
```
as expected. I have put together some support for it using a modified version of https://github.com/mike820324/socks5 (due to https://github.com/mike820324/socks5/issues/16). Is it worth improving this into a proper PR or is this outside the scope of hyper?

**Comment by Leezj9671** [comment]
Is SOCKS5 proxy cool in hyper now?

**Comment by matsjoyce** [comment]
A different route to try is https://github.com/encode/httpx/, which also doesn't have SOCKS5 support, but is being maintained. Hopefully they might implement it soon?

**Comment by Leezj9671** [comment]
You can use httpx-socks if using httpx

matsjoyce <notifications@github.com> 于 2020年12月26日周六 下午6:11写道：

**Comment by sethmlarson** [comment]
Hyper is not likely to add new features, the project is not under development any more.
