### ISSUE TITLE
Enable processing for SETTINGS_MAX_FRAME_SIZE.

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#69]
We should be able to offer the ability to send us larger frames if users want it. This is an obvious foot gun so it needs to not be too easy to do, but it should be possible.

Suggested API:

```python
c = HTTP20Connection()
c.max_frame_size = 2**22
```

This should cause updated settings and the emission of the appropriate SETTINGS frame. Additionally, we should add validation of decoded frame lengths and reject anything that's too long.

**Comment by jdecuyper** [comment]
@Lukasa

Initially the maximum frame size is `2^14-1`. This value can be changed by the endpoint (when receiving a settings frame) or by the client itself (using the `max_frime_size` property as you mention above).

When consuming a single frame (inside `connection.py`), I have added a check against the current max frame size:
```
frame_size = self._settings[SettingsFrame.SETTINGS_MAX_FRAME_SIZE]
if (length > frame_size):
    f = RstStreamFrame(frame.stream_id)
    f.error_code = 6 # FRAME_SIZE_ERROR
    self._send_cb(f)
    log.warning(
        "Frame size exceeded on stream %d (received: %d, max: %d)",
        stream_id,
        length,
        frame_size
        )
```
So far so good or any comments before continuing?  :)
I guess we should put a similar check when calling `_send_cb`?

**Comment by Lukasa** [comment]
Whenever we send an `RstStreamFrame` we should delete the associated stream from our stream map. It may be worth pulling that into a helper method, as I believe we do similar things elsewhere in the code.

**Comment by jdecuyper** [comment]
Yes, I'm going to add the following utility method to the connection class itself:
```
_send_rst_frame(stream_id, error_code)
   # send reset stream frame
   # remove stream from map
```
I detected already 5 potential calls to this method.

**Comment by jdecuyper** [comment]
What I still need to add:
* `max_frame_size` property: using it will update the setting and cause the emission of the appropriate SETTINGS frame to the server.
* We should also check against max frame size when calling `_send_cb`, right?

**Comment by Lukasa** [comment]
Let's do the `max_frame_size` property later, I don't think it's a high priority feature, and we want to handle it really carefully so that we can extend it to other settings.

As I note in my review, we definitely need to check against max frame size.

**Comment by jdecuyper** [comment]
@Lukasa thanks for in depth review, will work on changes and come back.

What other feature would you consider high priority and being easy or intermediate to implement?

**Comment by Lukasa** [comment]
Actually, scanning through the list, this might be the highest priority. =D

**Comment by Lukasa** [comment]
This is done now. =)
