### ISSUE TITLE
Better TLS

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#8]
We should make it easier to provide your own certificates for verification.

**Comment by jdecuyper** [comment]
@Lukasa Could you elaborate a bit more on this feature? A property to update the path to the `certs.pem` file?

**Comment by Lukasa** [comment]
Basically, something like the `verify` parameter that requests has was the original plan.

At this point though, I think the correct thing to do is to make it possible to provide an external `SSLContext` object.
