### ISSUE TITLE
Add support for proxies.

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#86]
It would be nice if we supported connecting via proxies, both HTTP/2 and HTTP/1.1.

**Comment by fredthomsen** [comment]
I have started to look into this.

**Comment by Lukasa** [comment]
Awesome! Shout if you run into trouble or want advice, or hop into #python-requests on Freenode, where I spend a lot of time.

**Comment by fredthomsen** [comment]
Would a bypass list for a session be worth including into this?

**Comment by Lukasa** [comment]
I don't think so. =)

The way this normally works is that for a library at this level you just say "give me a proxy" or "don't give me a proxy". Higher-level libraries like requests worry about more complex function like exclusions

**Comment by fredthomsen** [comment]
Finally got back around to this after some distractions.  Making a pull request to make sure I am on the right track.
