### ISSUE TITLE
Throw better error for NPN failure.

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#95]
Following on from #94.

**Comment by jdecuyper** [comment]
@Lukasa if the NPN version is not supported, would it be best to raise an error or display a debug statement?

In case of raising an error, I would add the following:
````
if ssl_sock.selected_npn_protocol() not in H2_NPN_PROTOCOLS:
       raise NPNError("NPN is not supported. Supported NPN versions: %s" %
       ', '.join(H2_NPN_PROTOCOLS))
```

**Comment by Lukasa** [comment]
@jdecuyper I think we need an 'ERROR' level log that says what NPN protocol was selected. I'm happy to leave the rest alone right now, as I'll shortly rewrite part of that code to handle upgrade logic instead.

**Comment by jdecuyper** [comment]
We can check if the NPN protocol is supported and only then log the error:
```
if proto not in H2_NPN_PROTOCOLS:
   log.error("Selected NPN protocol is not supported: %s", proto)
assert proto in H2_NPN_PROTOCOLS
```
...or always display the selected NPN protocol when debugging is enabled:
```
log.debug("Selected NPN protocol: %s", proto)
assert proto in H2_NPN_PROTOCOLS
```
I believe the second approach is more useful, what would you recommend?

**Comment by Lukasa** [comment]
Agreed, I think the second approach is better.
