### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'

### ISSUE THREAD

**Issue by zablotski** [Lukasa/hyper#99]
Hello. I have problem with readme example.
OS: Mint 17.1 
Python: 2.7
```python
Traceback (most recent call last):
  File "hyper_test.py", line 4, in <module>
    conn.request('GET', '/')
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 149, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 310, in endheaders
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 204, in connect
    sock = wrap_socket(sock, self.host)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/tls.py", line 33, in wrap_socket
    _context = _init_context()
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/tls.py", line 53, in _init_context
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
````
I have no experience with python, maybe I'm doing something wrong.
Regards, 
Yevgeny

**Comment by Lukasa** [comment]
Thanks for opening this issue Yevgeny, and thanks for trying out `hyper`!

HTTP/2 sets some very strict standards for the security of the connection, and one of them is that it requires TLSv1.2 for all connections. The Python 2.7 standard library does not provide access to this TLS level in any version earlier than 2.7.9, which means that `hyper` only supports Python 2.7.9 or Python 3.4+.

I recommend, if possible, either updating your Python 2.7 version or installing Python 3.4. It seems that on Linux Mint you can get Python 3.4 by installing the `python3` package. You can therefore get everything installed by running:

```bash
$ apt-get install python3 python3-pip
$ pip-3.4 install hyper
```

(Not sure if pip will actually get installed as pip-3.4, but it will get a name that is something like that.)

Then, use your new `python3` executable to try again.

**Comment by zablotski** [comment]
Thanks, it works fine for me.
P.S. In my environment alias for ```pip-3.4``` is ```pip3``` :wink:

**Comment by Lukasa** [comment]
Excellent, I'm glad I'm able to help!

Hopefully the next release of Linux Mint will upgrade to Python 2.7.9, which will be a substantial improvement. =)

**Comment by skaushikpowershell** [comment]
Same issue in centos. Can someone please help
